-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2016-11-28 10:49:12 EST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE legacy_codeEnfEvent
  (
    eventID                     INTEGER NOT NULL ,
    eventDate                   DATE ,
    eventDescription            VARCHAR (500) ,
    complianceDate              DATE ,
    letterText                  VARCHAR (2000) ,
    codeOfficer_officerID       INTEGER NOT NULL ,
    codeEnfCase_caseID          INTEGER NOT NULL ,
    EventTyp_codeEnfEventTypeID INTEGER NOT NULL ,
    lastUpdated                 DATE ,
    codeEnfLetter_letterID      INTEGER
  ) ;
CREATE UNIQUE INDEX legacy_codeEnfEvent__IDX ON codeEnfEvent
  (
    eventID ASC
  )
  ;
ALTER TABLE codeEnfEvent ADD CONSTRAINT codeEnfEvent_PK PRIMARY KEY ( eventID ) ;



CREATE TABLE legacy_codeOfficer
  (
    officerID       INTEGER NOT NULL ,
    firstName       VARCHAR (50) NOT NULL ,
    lastName        VARCHAR (50) NOT NULL ,
    hireDate        DATE ,
    workEndDate     DATE ,
    roleDescription VARCHAR (100) NOT NULL
  ) ;
ALTER TABLE codeOfficer ADD CONSTRAINT codeOfficer_PK PRIMARY KEY ( officerID ) ;


CREATE TABLE legacy_inspecChecklist
  ( checklistID INTEGER NOT NULL,
    Roof VARCHAR (100) ,
    Roof_VID VARCHAR (100) ,
    RainGutters VARCHAR (100) ,
    RainGutters_VID VARCHAR (100) ,
    DownSpouts VARCHAR (100) ,
    DownSpouts_VID VARCHAR (100) ,
    ExtWindows VARCHAR (100) ,
    ExtWindows_VID VARCHAR (100) ,
    WindowScreens VARCHAR (100) ,
    WindowScreens_VID VARCHAR (100) ,
    Doors VARCHAR (100) ,
    Doors_VID VARCHAR (100) ,
    DoorScreens VARCHAR (100) ,
    DoorScreens_VID VARCHAR (100) ,
    ExtRailings VARCHAR (100) ,
    ExtRailings_VID VARCHAR (100) ,
    Porch VARCHAR (100) ,
    Porch_VID VARCHAR (100) ,
    Sidewalks VARCHAR (100) ,
    Sidewalks_VID VARCHAR (100) ,
    Walls VARCHAR (100) ,
    Walls_VID VARCHAR (100) ,
    Ceiling VARCHAR (100) ,
    Ceiling_VID VARCHAR (100) ,
    Floors VARCHAR (100) ,
    Floors_VID VARCHAR (100) ,
    IntWindows VARCHAR (100) ,
    IntWindows_VID VARCHAR (100) ,
    Stairs VARCHAR (100) ,
    Stairs_VID VARCHAR (100) ,
    IntRailings VARCHAR (100) ,
    IntRailings_VID VARCHAR (100) ,
    SmokeDetectorsBed1 VARCHAR (100) ,
    SmokeDetectorsBed2 VARCHAR (100) ,
    SmokeDetectorsBed3 VARCHAR (100) ,
    SmokeDetectorsOther VARCHAR (100) ,
    SmokeDetectors_VID VARCHAR (100) ,
    CODetectors VARCHAR (100) ,
    CODetectors_VID VARCHAR (100) ,
    GeneralSanitation VARCHAR (100) ,
    GeneralSanitation_VID VARCHAR (100) ,
    Mold_Mildew VARCHAR (100) ,
    Mold_Mildew_VID VARCHAR (100) ,
    Vermin VARCHAR (100) ,
    Vermin_VID VARCHAR (100) ,
    Trash_Garbage VARCHAR (100) ,
    Trash_Garbage_VID VARCHAR (100) ,
    RecycleBins VARCHAR (100) ,
    RecycleBins_VID VARCHAR (100) ,
    KitchenFaucets VARCHAR (100) ,
    KitchenFaucets_VID VARCHAR (100) ,
    BathLavatory VARCHAR (100) ,
    BathLavatory_VID VARCHAR (100) ,
    BathTub VARCHAR (100) ,
    BathTub_VID VARCHAR (100) ,
    BathShower VARCHAR (100) ,
    BathShower_VID VARCHAR (100) ,
    LaundryTub VARCHAR (100) ,
    LaundryTub_VID VARCHAR (100) ,
    Toilet VARCHAR (100) ,
    Toilet_VID VARCHAR (100) ,
    ElectricalService VARCHAR (100) ,
    ElectricalService_VID VARCHAR (100) ,
    IdentifyAllBreakers VARCHAR (100) ,
    IdentifyAllBreakers_VID VARCHAR (100) ,
    Switches_CoverPlates VARCHAR (100) ,
    Switches_CoverPlates_VID VARCHAR (100) ,
    Receptacles_CoverPlates VARCHAR (100) ,
    Receptacles_CoverPlates_VID VARCHAR (100) ,
    GFCIs VARCHAR (100) ,
    GFCIs_VID VARCHAR (100) ,
    KitchenElectric VARCHAR (100) ,
    KitchenElectric_VID VARCHAR (100) ,
    BathRoomElectric VARCHAR (100) ,
    BathRoomElectric_VID VARCHAR (100) ,
    CeilingLights VARCHAR (100) ,
    CeilingLights_VID VARCHAR (100) ,
    ExteriorLights VARCHAR (100) ,
    ExteriorLights_VID VARCHAR (100) ,
    Laundry VARCHAR (100) ,
    Laundry_VID VARCHAR (100) ,
    StairwayLights VARCHAR (100) ,
    StairwayLights_VID VARCHAR (100) ,
    GeneralFurnace VARCHAR (100) ,
    GeneralFurnace_VID VARCHAR (100) ,
    FurnaceVent_Exhaust VARCHAR (100) ,
    FurnaceVent_Exhaust_VID VARCHAR (100) ,
    Thermostat VARCHAR (100) ,
    Thermostat_VID VARCHAR (100) ,
    GeneralHotWaterTank VARCHAR (100) ,
    GeneralHotWaterTank_VID VARCHAR (100) ,
    HotWaterVent_Exhaust VARCHAR (100) ,
    HotWaterVent_Exhaust_VID VARCHAR (100) ,
    TPSafetyValve VARCHAR (100) ,
    TPSafetyValve_VID VARCHAR (100) ,
    BlowOff6inFromFloor VARCHAR (100) ,
    BlowOff6inFromFloor_VID VARCHAR (100) ,
    Controller VARCHAR (100) ,
    Controller_VID VARCHAR (100) ,
    RoofComment VARCHAR (100) ,
    RainGuttersComment VARCHAR (100) ,
    DownSpoutsComment VARCHAR (100) ,
    ExtWindowsComment VARCHAR (100) ,
    WindowScreensComment VARCHAR (100) ,
    DoorsComment VARCHAR (100) ,
    DoorScreensComment VARCHAR (100) ,
    ExtRailingsComment VARCHAR (100) ,
    PorchComment VARCHAR (100) ,
    SidewalksComment VARCHAR (100) ,
    WallsComment VARCHAR (100) ,
    CeilingComment VARCHAR (100) ,
    FloorsComment VARCHAR (100) ,
    IntWindowsComment VARCHAR (100) ,
    StairsComment VARCHAR (100) ,
    IntRailingsComment VARCHAR (100) ,
    SmokeDetectorsComment VARCHAR (100) ,
    CODetectorsComment VARCHAR (100) ,
    GeneralSanitationComment VARCHAR (100) ,
    Mold_MildewComment VARCHAR (100) ,
    VerminComment VARCHAR (100) ,
    Trash_GarbageComment VARCHAR (100) ,
    RecycleBinsComment VARCHAR (100) ,
    KitchenFaucetsComment VARCHAR (100) ,
    BathLavatoryComment VARCHAR (100) ,
    BathTubComment VARCHAR (100) ,
    BathShowerComment VARCHAR (100) ,
    LaundryTubComment VARCHAR (100) ,
    ToiletComment VARCHAR (100) ,
    ElectricalServiceComment VARCHAR (100) ,
    IdentifyAllBreakersComment VARCHAR (100) ,
    Switches_CoverPlatesComment VARCHAR (100) ,
    Receptacles_CoverPlatesComment VARCHAR (100) ,
    GFCIsComment VARCHAR (100) ,
    KitchenElectricComment VARCHAR (100) ,
    BathroomElectricComment VARCHAR (100) ,
    CeilingLightsComment VARCHAR (100) ,
    ExteriorLightsComment VARCHAR (100) ,
    LaundryComment VARCHAR (100) ,
    StairwayLightsComment VARCHAR (100) ,
    GeneralFurnaceComment VARCHAR (100) ,
    FurnaceVent_ExhaustComment VARCHAR (100) ,
    ThermostatComment VARCHAR (100) ,
    GeneralHotWaterTankComment VARCHAR (100) ,
    HotWaterVent_ExhaustComment VARCHAR (100) ,
    TPSafetyValveComment VARCHAR (100) ,
    BlowOff6inFromFloorComment VARCHAR (100) ,
    ControllerComment VARCHAR (100)
 ) ;
ALTER TABLE inspecChecklist ADD CONSTRAINT inspecChecklist_PK PRIMARY KEY ( checklistID ) ;

-- let's try to connect to the existing muni table
CREATE TABLE municipality
  (
    municipalityID       INTEGER NOT NULL ,
    muniName             VARCHAR (50) NOT NULL ,
    officeMailingAddress VARCHAR (50) ,
    phone                VARCHAR (12) ,
    fax                  VARCHAR (12) ,
    managerName          VARCHAR (100) ,
    managerPhone         VARCHAR (12) ,
    occInspectionFee     MONEY,
    conductOccInspec     BOOLEAN
  ) ;
ALTER TABLE municipality ADD CONSTRAINT municipality_PK PRIMARY KEY ( municipalityID ) ;


CREATE TABLE occInspec
  (
    property_propertyID         INTEGER NOT NULL ,
    inspectionID                INTEGER NOT NULL ,
    occInspecRequest_requestID  INTEGER ,
    occPermitReason_reasonID    INTEGER NOT NULL ,
    unitNo                      VARCHAR (10) ,
    inspectionStatus_stausID    INTEGER NOT NULL ,
    firstInspectionDate         DATE ,
    reinspectionDate            DATE ,
    thirdInspectionDate         DATE ,
    inspectionPassDate          DATE ,
    inspectionComments          VARCHAR (300) ,
    inspecChecklist_checklistID INTEGER ,
    lastUpdated                 DATE ,
    inspContactName             VARCHAR (50) ,
    inspContactPhone            VARCHAR (15) ,
    inspContactEmail            VARCHAR (100)
  ) ;
CREATE UNIQUE INDEX occInspec__IDX ON occInspec
  (
    inspecChecklist_checklistID ASC
  )
  ;
ALTER TABLE occInspec ADD CONSTRAINT occInspec_PK PRIMARY KEY ( inspectionID ) ;


CREATE TABLE occInspecPhotoDoc
  (
    occInspec_inspectionID INTEGER NOT NULL ,
    photoDoc_photoDocID    INTEGER NOT NULL
  ) ;
ALTER TABLE occInspecPhotoDoc ADD CONSTRAINT occInspecPhotoDoc_PK PRIMARY KEY ( occInspec_inspectionID, photoDoc_photoDocID ) ;


CREATE TABLE occInspecRequest
  (
    requestID                   INTEGER NOT NULL ,
    municipality_municipalityID INTEGER NOT NULL ,
    inspectionAddress           VARCHAR (50) ,
    actionRequestor_requestorID INTEGER NOT NULL ,
    request_date                DATE ,
    description                 VARCHAR (100) ,
    additionalContactDetails    VARCHAR (100)
  ) ;
ALTER TABLE occInspecRequest ADD CONSTRAINT occInspecRequest_PK PRIMARY KEY ( requestID ) ;


CREATE TABLE occPermit
  (
    permitID               INTEGER NOT NULL ,
    permitNo               VARCHAR (10) ,
    dateIssued             DATE NOT NULL ,
    dateExpires            DATE ,
    permitComments         VARCHAR (100) ,
    occInspec_inspectionID INTEGER NOT NULL ,
    lastUpdated            DATE ,
    temporaryPermit        CHAR (1)
  ) ;

CREATE UNIQUE INDEX occPermit__IDX ON occPermit
  (
    occInspec_inspectionID ASC
  )  ;
ALTER TABLE occPermit ADD CONSTRAINT occPermit_PK PRIMARY KEY ( permitID ) ;


CREATE TABLE occPermitReason
  (
    reasonID          INTEGER NOT NULL ,
    reasonName        VARCHAR (50) NOT NULL ,
    reasonDescription VARCHAR (50)
  ) ;
ALTER TABLE occPermitReason ADD CONSTRAINT occPermitReason_PK PRIMARY KEY ( reasonID ) ;


CREATE TABLE payment
  (
    paymentId            INTEGER NOT NULL ,
    dateReceived         DATE NOT NULL ,
    dateDeposited        DATE ,
    amount               MONEY NULL ,
    payerName            VARCHAR (50) NOT NULL ,
    referenceNum         VARCHAR (50) NOT NULL ,
    PaymentType_typeId   INTEGER NOT NULL ,
    occInspec_inspection INTEGER NOT NULL
  ) ;
ALTER TABLE payment ADD CONSTRAINT payment_PK PRIMARY KEY ( paymentId ) ;


CREATE TABLE paymentPhotoDoc
  (
    photoDoc_photoDocID INTEGER NOT NULL ,
    payment_paymentId   INTEGER NOT NULL
  ) ;
ALTER TABLE paymentPhotoDoc ADD CONSTRAINT paymentPhotoDoc_PK PRIMARY KEY ( photoDoc_photoDocID, payment_paymentId ) ;


CREATE TABLE photoDoc
  (
    photoDocID          INTEGER NOT NULL ,
    photoDocDescription VARCHAR (100) ,
    photoDocDate        DATE ,
    photoDocType_typeID INTEGER NOT NULL ,
    photoDocBlob        BYTEA
  ) ;
ALTER TABLE photoDoc ADD CONSTRAINT photoDoc_PK PRIMARY KEY ( photoDocID ) ;


CREATE TABLE photoDocType
  (
    typeID          INTEGER NOT NULL ,
    TypeName        VARCHAR (50) ,
    typeDescription VARCHAR (100)
  ) ;
ALTER TABLE photoDocType ADD CONSTRAINT photoDocType_PK PRIMARY KEY ( typeID ) ;


CREATE TABLE property
  (
    propertyID                    INTEGER NOT NULL ,
    parID                         VARCHAR (15) ,
    lotAndBlock                   VARCHAR (15) ,
    rental                        BOOLEAN,
    address                       VARCHAR (100) ,
    apartmentNo                   VARCHAR (50) ,
    propertyAgent_agentID         INTEGER ,
    municipality_municipalityID   INTEGER NOT NULL ,
    propertyUseType_propertyUseID INTEGER,
    propertyOwner_ownerID         INTEGER NOT NULL
  ) ;
ALTER TABLE property ADD CONSTRAINT property_PK PRIMARY KEY ( propertyID ) ;


CREATE TABLE legacy_propertyAgent
  (
    agentID        INTEGER NOT NULL ,
    agentFirstName VARCHAR (50) NOT NULL ,
    agentLastName  VARCHAR (50) NOT NULL ,
    mailingAddress VARCHAR (50) ,
    mailingCity    VARCHAR (50) ,
    mailingState   VARCHAR (2) ,
    mailingZipcode INTEGER ,
    phone          VARCHAR (50) ,
    email          VARCHAR (100) ,
    fax            VARCHAR (2) ,
    notes          VARCHAR (100)
  ) ;
ALTER TABLE propertyAgent ADD CONSTRAINT propertyAgent_PK PRIMARY KEY ( agentID ) ;


CREATE TABLE propertyOwner
  (
    ownerID               INTEGER NOT NULL ,
    ownerFullname         VARCHAR (200) NOT NULL ,
    ownerAddress          VARCHAR (200) ,
    ownerCity             VARCHAR (50) ,
    ownerState            VARCHAR (2) ,
    ownerZIPCode          VARCHAR (10) ,
    ownerPhone            VARCHAR (15) ,
    ownerEmail            VARCHAR (100) ,
    ownerNameFrmCounty    VARCHAR (100) ,
    ownerAddrFrmCounty    VARCHAR (200) ,
    ownerCityFrmCounty    VARCHAR (50) ,
    ownerStateFrmCounty   VARCHAR (2) ,
    ownerZipCodeFrmCounty VARCHAR (10) ,
    lastUpdated           DATE NOT NULL
  ) ;
ALTER TABLE propertyOwner ADD CONSTRAINT propertyOwner_PK PRIMARY KEY ( ownerID ) ;


CREATE TABLE propertyPhotoDoc
  (
    photoDoc_photoDocID INTEGER NOT NULL ,
    property_propertyID INTEGER NOT NULL
  ) ;
ALTER TABLE propertyPhotoDoc ADD CONSTRAINT propertyPhotoDoc_PK PRIMARY KEY ( photoDoc_photoDocID, property_propertyID ) ;


CREATE TABLE propertyUseType
  (
    propertyUseID  INTEGER NOT NULL ,
    useName        VARCHAR (50) NOT NULL ,
    useDescription VARCHAR (100)
  ) ;
ALTER TABLE propertyUseType ADD CONSTRAINT propertyUseType_PK PRIMARY KEY ( propertyUseID ) ;


CREATE TABLE tenant
  (
    lesseeID                     INTEGER NOT NULL ,
    firstName                    VARCHAR (50) NOT NULL ,
    lastName                     VARCHAR (50) NOT NULL ,
    phone                        VARCHAR (15) ,
    currentTenant                BOOLEAN ,
    under18                      BOOLEAN ,
    occPermit_permitID           INTEGER ,
    disruptiveConduct_incidentID INTEGER
  ) ;
COMMENT ON COLUMN tenant.occPermit_permitID
IS
  'accessDB field mapping: tblRentalPermit.RentalID' ;
ALTER TABLE tenant ADD CONSTRAINT tenant_PK PRIMARY KEY ( lesseeID ) ;

ALTER TABLE codeEnfCaseViolation ADD CONSTRAINT FK_ASS_32 FOREIGN KEY ( codeViolation_violationID ) REFERENCES codeViolation ( violationID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfCaseViolation ADD CONSTRAINT FK_ASS_33 FOREIGN KEY ( codeEnfCase_caseID ) REFERENCES codeEnfCase ( caseID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfEventPhotoDoc ADD CONSTRAINT FK_ASS_36 FOREIGN KEY ( photoDoc_photoDocID ) REFERENCES photoDoc ( photoDocID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfEventPhotoDoc ADD CONSTRAINT FK_ASS_37 FOREIGN KEY ( codeEnfEvent_eventID ) REFERENCES codeEnfEvent ( eventID ) NOT DEFERRABLE ;

ALTER TABLE courtCasephotoDoc ADD CONSTRAINT FK_ASS_40 FOREIGN KEY ( photoDoc_photoDocID ) REFERENCES photoDoc ( photoDocID ) NOT DEFERRABLE ;

ALTER TABLE courtCasephotoDoc ADD CONSTRAINT FK_ASS_41 FOREIGN KEY ( courtCase_courtCaseID ) REFERENCES courtCase ( courtCaseID ) NOT DEFERRABLE ;

ALTER TABLE muni_codeOff ADD CONSTRAINT FK_ASS_44 FOREIGN KEY ( municipality_municipalityID ) REFERENCES municipality ( municipalityID ) NOT DEFERRABLE ;

ALTER TABLE muni_codeOff ADD CONSTRAINT FK_ASS_45 FOREIGN KEY ( codeOfficer_officerID ) REFERENCES codeOfficer ( officerID ) NOT DEFERRABLE ;

ALTER TABLE occInspecPhotoDoc ADD CONSTRAINT FK_ASS_48 FOREIGN KEY ( occInspec_inspectionID ) REFERENCES occInspec ( inspectionID ) NOT DEFERRABLE ;

ALTER TABLE occInspecPhotoDoc ADD CONSTRAINT FK_ASS_49 FOREIGN KEY ( photoDoc_photoDocID ) REFERENCES photoDoc ( photoDocID ) NOT DEFERRABLE ;

ALTER TABLE propertyPhotoDoc ADD CONSTRAINT FK_ASS_52 FOREIGN KEY ( photoDoc_photoDocID ) REFERENCES photoDoc ( photoDocID ) NOT DEFERRABLE ;

ALTER TABLE propertyPhotoDoc ADD CONSTRAINT FK_ASS_53 FOREIGN KEY ( property_propertyID ) REFERENCES property ( propertyID ) NOT DEFERRABLE ;

ALTER TABLE disCondPhotoDoc ADD CONSTRAINT TABLE_42_photoDoc_FK FOREIGN KEY ( photoDoc_photoDocID ) REFERENCES photoDoc ( photoDocID ) NOT DEFERRABLE ;

ALTER TABLE tenant ADD CONSTRAINT "`" FOREIGN KEY ( disruptiveConduct_incidentID ) REFERENCES disruptiveConduct ( incidentID ) NOT DEFERRABLE ;

ALTER TABLE actionRequestor ADD CONSTRAINT actionRqstr_actionRqstrType_FK FOREIGN KEY ( actionRequestorType_typeID ) REFERENCES actionRequestorType ( typeID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfActionRequest ADD CONSTRAINT cdEnfActnRqst_actionRqstr_FK FOREIGN KEY ( actionRequestor_requestorID ) REFERENCES actionRequestor ( requestorID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfActionRequest ADD CONSTRAINT cdEnfActnRqst_actnRqstIssTp_FK FOREIGN KEY ( issueTypeID ) REFERENCES actionRqstIssueType ( issueTypeID ) NOT DEFERRABLE ;

ALTER TABLE codeViolation ADD CONSTRAINT cdViol_codeViolTp_FK FOREIGN KEY ( codeViolType_codeViolTypeID ) REFERENCES codeViolationType ( codeViolationTypeID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfActionRequest ADD CONSTRAINT codeEnfActRqst_munic_FK FOREIGN KEY ( municipality_municipalityID ) REFERENCES municipality ( municipalityID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfCase ADD CONSTRAINT codeEnfCase_codeEnfActRqst_FK FOREIGN KEY ( codeEnfActionRqst_requestID ) REFERENCES codeEnfActionRequest ( requestID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfCase ADD CONSTRAINT codeEnfCase_codeEnfCsStatus_FK FOREIGN KEY ( CaseStatus_ceEventStatusID ) REFERENCES codeEnfCaseStatus ( ceEventStatusID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfCase ADD CONSTRAINT codeEnfCase_codeOfficer_FK FOREIGN KEY ( codeOfficer_officerID ) REFERENCES codeOfficer ( officerID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfCase ADD CONSTRAINT codeEnfCase_courtCase_FK FOREIGN KEY ( courtCase_courtCaseID ) REFERENCES courtCase ( courtCaseID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfCase ADD CONSTRAINT codeEnfCase_property_FK FOREIGN KEY ( property_propertyID ) REFERENCES property ( propertyID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfEvent ADD CONSTRAINT codeEnfEvent_codeEnfCase_FK FOREIGN KEY ( codeEnfCase_caseID ) REFERENCES codeEnfCase ( caseID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfEvent ADD CONSTRAINT codeEnfEvent_codeEnfEvntTp_FK FOREIGN KEY ( EventTyp_codeEnfEventTypeID ) REFERENCES codeEnfEventType ( codeEnfEventTypeID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfEvent ADD CONSTRAINT codeEnfEvent_codeEnfLetter_FK FOREIGN KEY ( codeEnfLetter_letterID ) REFERENCES codeEnfLetter ( letterID ) NOT DEFERRABLE ;

ALTER TABLE codeEnfEvent ADD CONSTRAINT codeEnfEvent_codeOfficer_FK FOREIGN KEY ( codeOfficer_officerID ) REFERENCES codeOfficer ( officerID ) NOT DEFERRABLE ;

ALTER TABLE disCondPhotoDoc ADD CONSTRAINT disCondPhotoDoc_disCond_FK FOREIGN KEY ( disCond_incidentID ) REFERENCES disruptiveConduct ( incidentID ) NOT DEFERRABLE ;

ALTER TABLE disruptiveConduct ADD CONSTRAINT disCond_disCondCaseStatus_FK FOREIGN KEY ( caseStatus ) REFERENCES disrupCondCaseStatus ( statusID ) NOT DEFERRABLE ;

ALTER TABLE disruptiveConduct ADD CONSTRAINT disCond_disCondLetter_FK FOREIGN KEY ( disCondLetter_disCondLetterID ) REFERENCES disCondLetter ( disCondLetterID ) NOT DEFERRABLE ;

ALTER TABLE occInspecRequest ADD CONSTRAINT occInspecRqst_actionRqstr_FK FOREIGN KEY ( actionRequestor_requestorID ) REFERENCES actionRequestor ( requestorID ) NOT DEFERRABLE ;

ALTER TABLE occInspecRequest ADD CONSTRAINT occInspecRqst_municipality_FK FOREIGN KEY ( municipality_municipalityID ) REFERENCES municipality ( municipalityID ) NOT DEFERRABLE ;

ALTER TABLE occInspec ADD CONSTRAINT occInspec_inspecChecklist_FK FOREIGN KEY ( inspecChecklist_checklistID ) REFERENCES inspecChecklist ( checklistID ) NOT DEFERRABLE ;

ALTER TABLE occInspec ADD CONSTRAINT occInspec_inspectionStatus_FK FOREIGN KEY ( inspectionStatus_stausID ) REFERENCES inspectionStatus ( stausID ) NOT DEFERRABLE ;

ALTER TABLE occInspec ADD CONSTRAINT occInspec_occInspecRequest_FK FOREIGN KEY ( occInspecRequest_requestID ) REFERENCES occInspecRequest ( requestID ) NOT DEFERRABLE ;

ALTER TABLE occInspec ADD CONSTRAINT occInspec_occPermitReason_FK FOREIGN KEY ( occPermitReason_reasonID ) REFERENCES occPermitReason ( reasonID ) NOT DEFERRABLE ;

ALTER TABLE occInspec ADD CONSTRAINT occInspec_property_FK FOREIGN KEY ( property_propertyID ) REFERENCES property ( propertyID ) NOT DEFERRABLE ;

ALTER TABLE occPermit ADD CONSTRAINT occPermit_occInspec_FK FOREIGN KEY ( occInspec_inspectionID ) REFERENCES occInspec ( inspectionID ) NOT DEFERRABLE ;

ALTER TABLE payment ADD CONSTRAINT payment_PaymentType_FK FOREIGN KEY ( PaymentType_typeId ) REFERENCES PaymentType ( typeId ) NOT DEFERRABLE ;

ALTER TABLE payment ADD CONSTRAINT payment_occInspec_FK FOREIGN KEY ( occInspec_inspection ) REFERENCES occInspec ( inspectionID ) NOT DEFERRABLE ;

ALTER TABLE paymentPhotoDoc ADD CONSTRAINT payment_photoDOc_payment_FK FOREIGN KEY ( payment_paymentId ) REFERENCES payment ( paymentId ) NOT DEFERRABLE ;

ALTER TABLE paymentPhotoDoc ADD CONSTRAINT payment_photoDOc_photoDoc_FK FOREIGN KEY ( photoDoc_photoDocID ) REFERENCES photoDoc ( photoDocID ) NOT DEFERRABLE ;

ALTER TABLE photoDoc ADD CONSTRAINT photoDoc_photoDocType_FK FOREIGN KEY ( photoDocType_typeID ) REFERENCES photoDocType ( typeID ) NOT DEFERRABLE ;

ALTER TABLE property ADD CONSTRAINT property_municipality_FK FOREIGN KEY ( municipality_municipalityID ) REFERENCES municipality ( municipalityID ) NOT DEFERRABLE ;

ALTER TABLE property ADD CONSTRAINT property_propertyAgent_FK FOREIGN KEY ( propertyAgent_agentID ) REFERENCES propertyAgent ( agentID ) NOT DEFERRABLE ;

ALTER TABLE property ADD CONSTRAINT property_propertyOwner_FK FOREIGN KEY ( propertyOwner_ownerID ) REFERENCES propertyOwner ( ownerID ) NOT DEFERRABLE ;

ALTER TABLE property ADD CONSTRAINT property_propertyUseType_FK FOREIGN KEY ( propertyUseType_propertyUseID ) REFERENCES propertyUseType ( propertyUseID ) NOT DEFERRABLE ;

ALTER TABLE tenant ADD CONSTRAINT tenant_occPermit_FK FOREIGN KEY ( occPermit_permitID ) REFERENCES occPermit ( permitID ) NOT DEFERRABLE ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            40
-- CREATE INDEX                             6
-- ALTER TABLE                             89
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
