version: "3"
services:
  db:
    image: codenforce_db
    environment: 
      POSTGRES_DB: cog_db
      POSTGRES_USER: changeme
      POSTGRES_PASSWORD: changeme
    volumes:
     - ./db/pg-data/pg-data:/pg-data
     - cnf:/home/techred4/codenforce/
 #   - ./db/docker-entrypoint-initdb.d/test.sh
    ports:
    - "5432:5432"     
volumes: 
  cnf: 


