version: "3.9"
services:
  db:
    build: db
    ports:
      - "5432:5432"
    volumes:
      - ./db/pg-data/pg-data:/pg-data
  wildfly:
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    volumes:
      - ./target/war/:/opt/jboss/wildfly/standalone/deployments/
    depends_on:
      - db