DROP TABLE IF EXISTS codesetelement CASCADE;
DROP TABLE IF EXISTS codeelement CASCADE;
DROP TABLE IF EXISTS codeset CASCADE;
DROP TABLE IF EXISTS codesource CASCADE;
DROP TABLE IF EXISTS codeelementtype CASCADE;
DROP TABLE IF EXISTS propertyphotodoc CASCADE;
DROP TABLE IF EXISTS photodoc CASCADE;
DROP TABLE IF EXISTS codeviolation CASCADE;
DROP TABLE IF EXISTS citation CASCADE;
DROP TABLE IF EXISTS courtentity CASCADE;
DROP TABLE IF EXISTS ceeventperson CASCADE;
DROP TABLE IF EXISTS ceeventcategory CASCADE;
DROP TABLE IF EXISTS cecase CASCADE;
DROP TABLE IF EXISTS ceevent CASCADE;
DROP TABLE IF EXISTS propertyperson CASCADE;
DROP TABLE IF EXISTS propertyunit CASCADE;
DROP TABLE IF EXISTS propertyunitperson CASCADE;
DROP TABLE IF EXISTS propertyusetype CASCADE;
DROP TABLE IF EXISTS enforcementofficial CASCADE;
DROP TABLE IF EXISTS login CASCADE;
DROP TABLE IF EXISTS ceactionrequest CASCADE;
DROP TABLE IF EXISTS actionrqstissuetype CASCADE;
DROP TABLE IF EXISTS propertyexternaldata CASCADE;
DROP TABLE IF EXISTS property CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS municipality CASCADE; 
DROP TABLE IF EXISTS coglog CASCADE;

DROP SEQUENCE IF EXISTS photodoc_photoDocID_seq;
DROP SEQUENCE IF EXISTS codeviolation_violationID_seq;
DROP SEQUENCE IF EXISTS codeviolationtype_cvTypeID_seq;
DROP SEQUENCE IF EXISTS codesource_sourceID_seq;
DROP SEQUENCE IF EXISTS cecaseviolation_caseViolationID_seq;
DROP SEQUENCE IF EXISTS ceevent_eventID_seq;
DROP SEQUENCE IF EXISTS cecase_caseID_seq;
DROP SEQUENCE IF EXISTS ceeventcategory_categoryID_seq;
DROP SEQUENCE IF EXISTS propertunit_unitID_seq;
DROP SEQUENCE IF EXISTS propertyusetype_seq;
DROP SEQUENCE IF EXISTS login_userid_seq;
DROP SEQUENCE IF EXISTS ceactionrequest_requestid_seq;
DROP SEQUENCE IF EXISTS actionrqstissuetype_issueTypeID_seq;
DROP SEQUENCE IF EXISTS person_personIDSeq;
DROP SEQUENCE IF EXISTS coglog_logeEntryID_seq;
DROP SEQUENCE IF EXISTS enforcementofficial_officialID_seq;
DROP SEQUENCE IF EXISTS codesource_sourceID_seq;
DROP SEQUENCE IF EXISTS codeelementtype_cvTypeID_seq;
DROP SEQUENCE IF EXISTS codeset_codeSetID_seq;
DROP SEQUENCE IF EXISTS codeelement_elementID_seq;
DROP SEQUENCE IF EXISTS citation_citationID_seq;
DROP SEQUENCE IF EXISTS courtentity_entityID_seq;
DROP SEQUENCE IF EXISTS propertyexternaldata_extDataID_seq;
DROP SEQUENCE IF EXISTS codesetelement_elementid_seq ;


DROP TYPE IF EXISTS personType;
DROP TYPE IF EXISTS role;
DROP TYPE IF EXISTS casephase;
DROP TYPE IF EXISTS ceEventType;
