# Todo: Move functions from parcelupdate into create
from _constants import BOT_ID


def cecase_imap(prop_id, unit_id):
    # These should be filled out by the subclass
    imap = {}
    imap["cecasepubliccc"] = 111111
    imap["property_propertyid"] = prop_id
    imap["propertyunit_unitid"] = unit_id
    imap["login_userid"] = BOT_ID
    imap["casename"] = "Property Info Case"
    imap["notes"] = "Autogenerated."
    imap["casephase"] = None
    imap["paccenabled"] = False
    imap["allowuplinkaccess"] = None
    imap["propertyinfocase"] = True
    imap["personinfocase_personid"] = None
    imap["bobsource_sourceid"] = None
    imap["active"] = True
    return imap
