/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tcvcog.tcvce.entities.search;

import com.tcvcog.tcvce.entities.RoleType;

/**
 *
 * @author sylvia
 */
public  enum            QueryEventEnum 
        implements      IFace_RankLowerBounded{
    
    REQUESTED_ACTIONS(                  "Requested violation follow-up actions", 
                                        "System-generated events dated at the expiration of code violation compliance timeframes", 
                                        RoleType.MuniReader, 
                                        true,
                                        false),
    
    MUNI_MONTHYACTIVITY                 ("All system activity by Muni in the past 30 days", 
                                        "Events generated by the current municipality's default code officer in the past 30 days", 
                                        RoleType.MuniReader, 
                                        true,
                                        false),
    MUNI_24HR_ACTIVITY                 ("All system activity by Muni in the past 24 hours", 
                                        "Events generated by the current municipality's default code officer in the past 24 hours", 
                                        RoleType.MuniReader, 
                                        true,
                                        false),
    MUNI_7DAY_ACTIVITY                 ("All system activity by Muni in the past 7 days", 
                                        "Events generated by the current municipality's default code officer in the past 7 calendar days", 
                                        RoleType.MuniReader, 
                                        true,
                                        false),
    MUINI_FUTURE_7DAYS                 ("Future events in the coming 7 days", 
                                        "Events scheduled some time in the next week", 
                                        RoleType.MuniReader, 
                                        true,
                                        false),
    
    COMPLIANCE_EVENTS(                  "Violation compliance events: Past 30 days", 
                                        "Events detailing any code violation marked with compliance in the past 30 days", 
                                        RoleType.MuniReader, 
                                        true,
                                        false),
    
    OCCPERIOD(                          "Events by occ period",
                                        "All events by period",
                                        RoleType.MuniReader,
                                        false,
                                        false),
    
    CECASE  (                          "Events by Code Enforcement case",
                                        "All events by case",
                                        RoleType.MuniReader,
                                        false,
                                        false),
    
    PERSONS(                           "Events associated with a given Person",
                                       "in any way or capacity",
                                        RoleType.MuniReader,
                                        false,
                                        false),
    
    CUSTOM(                             "Custom", 
                                        "Custom", 
                                        RoleType.MuniReader,
                                        true,
                                        true),
    
    CALENDAR(                           "Calendar - day", 
                                        "Daily Calendar", 
                                        RoleType.MuniReader,
                                        true,
                                        false);
    
    private final String title;
    private final String desc;
    private final RoleType requiredRoleMin;
    private final boolean log;
    private final boolean showAllControls;
    
    private QueryEventEnum(String t, String l, RoleType minRoleType, boolean lg, boolean showall){
        this.desc = l;
        this.title = t;
        if(minRoleType != null){
            this.requiredRoleMin = minRoleType;
        } else {
            this.requiredRoleMin = RoleType.MuniStaff;
        }
        this.log = lg;
        this.showAllControls = showall;
    }
    
    public String getDesc(){
        return desc;
    }
    
    public String getTitle(){
        return title;
    }

    
    public boolean logQueryRun(){
        return log;
    }

    @Override
    public RoleType getRequiredRoleMin() {
        return requiredRoleMin;
    }

    /**
     * @return the showAllControls
     */
    public boolean isShowAllControls() {
        return showAllControls;
    }
    
    
}
