/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tcvcog.tcvce.entities.search;

/**
 *
 * @author sylvia
 */
public enum QueryEventCECaseEnum {
    
    REQUESTED_ACTIONS("Requested violation follow-up actions", "System-generated events dated at the expiration of code violation compliance timeframes", 2, false),
    MUNICODEOFFICER_ACTIVITY_PAST30DAYS("Code officer actions: Past 30 days", "Events generated by the current municipality's default code officer in the past 30 days", 2, false),
    COMPLIANCE_EVENTS("Violation compliance events: Past 30 days", "Events detailing any code violation marked with compliance in the past 30 days", 2, false),
    CUSTOM("Cusomt", "Custom", 2, false);
    
    private final String title;
    private final String desc;
    private final int userRankMinimum;
    private final boolean log;
    
    private QueryEventCECaseEnum(String t, String l, int rnkMin, boolean lg){
        this.desc = l;
        this.title = t;
        this.userRankMinimum = rnkMin;
        this.log = lg;
    }
    
    public String getDesc(){
        return desc;
    }
    
    public String getTitle(){
        return title;
    }

    /**
     * @return the userRankMinimum
     */
    public int getUserRankMinimum() {
        return userRankMinimum;
    }
    
    
    public boolean logQueryRun(){
        return log;
    }
    
    
}
